DELETE http://localhost:3333/events/2/register
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNlbHNvYWxleGFuZHJlQGxpdmUuY29tIiwiZXhwIjoxNzExNTE4OTY5LCJ1c2VySWQiOjF9.kzADJK4QF2Szku4G_1ja3GoR2HK-0WbIcOLWZjjZu74
