POST http://localhost:3333/events
Content-Type: application/json
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNlbHNvYWxleGFuZHJlQGxpdmUuY29tIiwiZXhwIjoxNzExNTE2MTgwLCJ1c2VySWQiOjF9.9EKRoIpM8zv40OmYe7F4Agudf7W7kwJf61EDocqmJeA

{
  "name": "Event 13",
  "description": "Description 13",
  "location": "Location 13",
  "date": "2024-03-26T17:04:23-03:00"
}